# 微信小程序数据抓取服务配置

# 服务器配置
server:
  address: ":8081"            # 监听地址，格式为 IP:PORT
  readTimeout: 30s            # 请求读取超时时间
  writeTimeout: 30s           # 响应写入超时时间

# 微信小程序配置
wechat:
  appID: ""                   # 微信小程序AppID
  appSecret: ""               # 微信小程序AppSecret

# 抓取器配置
scraper:
  userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"  # 浏览器UA
  timeout: 30s                # 抓取超时时间
  maxConcurrency: 5           # 最大并发数
  retryTimes: 3               # 重试次数
  retryDelay: 2s              # 重试间隔

# 数据库配置
database:
  type: "sqlite"              # 数据库类型 (sqlite, mysql, postgres)
  host: "localhost"           # 数据库主机地址
  port: 3306                  # 数据库端口
  user: "root"                # 数据库用户名
  password: ""                # 数据库密码
  dbName: "wechat_mini_data"  # 数据库名称

# 日志配置
log:
  level: "info"  # debug, info, warn, error
  format: "text"  # text, json
  output: "stdout"  # stdout, file
  file_path: "logs/app.log"

# 截图分析配置
screenshot:
  max_file_size: 10485760  # 10MB
  supported_formats: ["png", "jpg", "jpeg"]
  analysis_timeout: 60 